# version: '3.8'

services:
  tileserver:
    image: maptiler/tileserver-gl:latest
    container_name: tileserver
    restart: unless-stopped
    ports:
      - "8085:8080"
    volumes:
      - ./data:/data
      - ./config:/config
    command: ["--config", "/config/config.json"]
